### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by kenrick95** [szrenwei/inline-manifest-webpack-plugin#10]
I'm trying out Webpack 4 beta, and with this plugin, it throws the following error:

```
[path]/node_modules/tapable/lib/Tapable.js:63
                throw new Error(`Plugin could not be registered at '${name}'. Hook was not found.\n` +
                ^

Error: Plugin could not be registered at 'html-webpack-plugin-before-html-processing'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatiblity layer for this hook, hook into 'this._pluginCompat'.
    at Compilation.plugin ([path]/node_modules/tapable/lib/Tapable.js:63:9)
    at Compilation.deprecated [as plugin] (internal/util.js:47:15)
    at [path]/node_modules/inline-manifest-webpack-plugin/index.js:13:21
    at SyncHook.eval [as call] (eval at create ([path]/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:17:1)
    at SyncHook.lazyCompileHook [as _call] ([path]/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.newCompilation ([path]/node_modules/webpack/lib/Compiler.js:400:26)
    at hooks.beforeCompile.callAsync.err ([path]/node_modules/webpack/lib/Compiler.js:432:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create ([path]/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] ([path]/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.compile ([path]/node_modules/webpack/lib/Compiler.js:427:28)
    at readRecords.err ([path]/node_modules/webpack/lib/Compiler.js:217:11)
    at Compiler.readRecords ([path]/node_modules/webpack/lib/Compiler.js:324:11)
    at hooks.run.callAsync.err ([path]/node_modules/webpack/lib/Compiler.js:214:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create ([path]/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
...
```

**Comment by sherlock1982** [comment]
Use the latest Webpack and Html-webpack-plugin version. Though there's another issue with this. 
It's similar to this https://github.com/numical/script-ext-html-webpack-plugin/issues/41

**Comment by almothafar** [comment]
A fork support webpack 4 is here: https://github.com/almothafar/webpack-inline-manifest-plugin

you can install it using `npm i webpack-inline-manifest-plugin -D`  so `webpack-inline-manifest-plugin` instead of `inline-manifest-webpack-plugin`

**Comment by szrenwei** [comment]
updated!!! please use the v4 of this plugin, sorry for update so late..
