### ISSUE TITLE
webpack4.8.1还是不行

### ISSUE THREAD

**Issue by mslmsl111** [szrenwei/inline-manifest-webpack-plugin#14]
release.../Users/mobike/Desktop/activity-vue/node_modules/inline-manifest-webpack-plugin/index.js:18
                .tapAsync('InlineManifestWebpackPlugin', function (data, cb) {
                 ^

TypeError: Cannot read property 'tapAsync' of undefined
    at /Users/mobike/Desktop/activity-vue/node_modules/inline-manifest-webpack-plugin/index.js:18:18
    at SyncHook.eval [as call] (eval at create (/Users/mobike/Desktop/activity-vue/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:13:1)
    at SyncHook.lazyCompileHook [as _call] (/Users/mobike/Desktop/activity-vue/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.newCompilation (/Users/mobike/Desktop/activity-vue/node_modules/webpack/lib/Compiler.js:438:26)
    at hooks.beforeCompile.callAsync.err (/Users/mobike/Desktop/activity-vue/node_modules/webpack/lib/Compiler.js:474:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mobike/Desktop/activity-vue/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/mobike/Desktop/activity-vue/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.compile (/Users/mobike/Desktop/activity-vue/node_modules/webpack/lib/Compiler.js:469:28)
    at readRecords.err (/Users/mobike/Desktop/activity-vue/node_modules/webpack/lib/Compiler.js:220:11)
    at Compiler.readRecords (/Users/mobike/Desktop/activity-vue/node_modules/webpack/lib/Compiler.js:342:11)
    at hooks.run.callAsync.err (/Users/mobike/Desktop/activity-vue/node_modules/webpack/lib/Compiler.js:217:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mobike/Desktop/activity-vue/node_modules/tapable/lib/HookCode

**Comment by leefsmp** [comment]
Same here, seems the plugin doesn't support webpack 4.x

**Comment by szrenwei** [comment]
@leefsmp 
@mslmsl111 

I have try webpack 4.8.1, it works, it seems you have't use HtmlWebpackPlugin:
```javascript
// this plugin need to put after HtmlWebpackPlugin
[
    new HtmlWebpackPlugin(),
    new InlineManifestWebpackPlugin()
]
````

**Comment by chenshishuo** [comment]
InlineManifestWebpackPlugin need to run after HtmlWebpackPlugin
