### ISSUE TITLE
problem with html-webpack-plugin

### ISSUE THREAD

**Issue by wulucxy** [szrenwei/inline-manifest-webpack-plugin#21]
```javascript
/work/FE/cc/node_modules/inline-manifest-webpack-plugin/index.js:18
                .tapAsync('InlineManifestWebpackPlugin', function (data, cb) {
                 ^

TypeError: Cannot read property 'tapAsync' of undefined
    at /work/FE/cc/node_modules/inline-manifest-webpack-plugin/index.js:18:18
    at SyncHook.eval [as call] (eval at create (/work/FE/cc/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:11:1)
    at SyncHook.lazyCompileHook (/work/FE/cc/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/work/FE/cc/node_modules/webpack/lib/Compiler.js:503:26)
    at hooks.beforeCompile.callAsync.err (/work/FE/cc/node_modules/webpack/lib/Compiler.js:539:29)
```

my config is:

```
plugins: [
    new WebpackPluginHashOutput(),
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: 'public/index.html',
      chunksSortMode: 'none',
    }),
    new InlineManifestWebpackPlugin('manifest'),
    new MiniCssExtractPlugin({
      filename: '[contenthash:22].css',
    }),
    new webpack.HashedModuleIdsPlugin(),
  ],
```

**Comment by wulucxy** [comment]
yeah，there is problem with `html-webpack-plugin@4.0.0 beta`，my fault。
