### ISSUE TITLE
problem in inline-manifest-webpack-plugin

### ISSUE THREAD

**Issue by taimoortahir7** [szrenwei/inline-manifest-webpack-plugin#23]
TypeError: Cannot read property 'tapAsync' of undefined
at F:\Zeeshan\dev_area\EME\Code\emergencme-nodejs\node_modules\inline-manifest-webpack-plugin\index.js:18:18
at SyncHook.eval (eval at create (F:\Zeeshan\dev_area\EME\Code\emergencme-nodejs\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:11:1)
at SyncHook.lazyCompileHook (F:\Zeeshan\dev_area\EME\Code\emergencme-nodejs\node_modules\tapable\lib\Hook.js:154:20)
at Compiler.newCompilation (F:\Zeeshan\dev_area\EME\Code\emergencme-nodejs\node_modules\webpack\lib\Compiler.js:581:26)
at hooks.beforeCompile.callAsync.err (F:\Zeeshan\dev_area\EME\Code\emergencme-nodejs\node_modules\webpack\lib\Compiler.js:617:29)
at AsyncSeriesHook.eval [as callAsync] (eval at create (F:\Zeeshan\dev_area\EME\Code\emergencme-nodejs\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
at AsyncSeriesHook.lazyCompileHook (F:\Zeeshan\dev_area\EME\Code\emergencme-nodejs\node_modules\tapable\lib\Hook.js:154:20)
at Compiler.compile (F:\Zeeshan\dev_area\EME\Code\emergencme-nodejs\node_modules\webpack\lib\Compiler.js:612:28)
at compiler.hooks.watchRun.callAsync.err (F:\Zeeshan\dev_area\EME\Code\emergencme-nodejs\node_modules\webpack\lib\Watching.js:76:18)
at _err0 (eval at create (F:\Zeeshan\dev_area\EME\Code\emergencme-nodejs\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:38:1)
at F:\Zeeshan\dev_area\EME\Code\emergencme-nodejs\node_modules\awesome-typescript-loader\src\watch-mode.ts:12:4
at AsyncSeriesHook.eval [as callAsync] (eval at create (F:\Zeeshan\dev_area\EME\Code\emergencme-nodejs\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:7:1)
at AsyncSeriesHook.lazyCompileHook (F:\Zeeshan\dev_area\EME\Code\emergencme-nodejs\node_modules\tapable\lib\Hook.js:154:20)
at Watching._go (F:\Zeeshan\dev_area\EME\Code\emergencme-nodejs\node_modules\webpack\lib\Watching.js:40:32)
at Watching.compiler.readRecords.err (F:\Zeeshan\dev_area\EME\Code\emergencme-nodejs\node_modules\webpack\lib\Watching.js:32:9)
at Compiler.readRecords (F:\Zeeshan\dev_area\EME\Code\emergencme-nodejs\node_modules\webpack\lib\Compiler.js:479:11)

**Comment by taimoortahir7** [comment]
My webpack version is latest (4.29.6) and inline-manifest-webpack-plugin version is (~4.0.2)

**Comment by bentyfon** [comment]
What's your html-webpack-plugin version @taimoortahir7 ?

Mine was working fine with 3.2.0, but since I updated it to 4.0.0-beta.11 I'm getting the same error as you are.

**Comment by dnutels** [comment]
Happens with webpack 5 as well.... when on 4.0.2

**Comment by DavideDaniel** [comment]
This error is just due to the ordering of plugins. Move the usage of inline plugin to be the last plugin for it to work properly. It's most likely running into issues with Html webpack plugin.

**Comment by sterling** [comment]
Seems to break with html-webpack-plugin v4.0.1

**Comment by silkfire** [comment]
Any update on this?

**Comment by szrenwei** [comment]
> Any update on this?

Please use react-dev-utils instead ( https://github.com/facebook/create-react-app/tree/master/packages/react-dev-utils#new-inlinechunkhtmlpluginhtmlwebpackplugin-htmlwebpackplugin-tests-regex ), it does the same thing.
