### ISSUE TITLE
Compatibility with html-webpack-plugin v4

### ISSUE THREAD

**Issue by kroko** [szrenwei/inline-manifest-webpack-plugin#25]
Does not work with html-webpack-plugin 4.x. Still works with 3.2.0.

Reason probably being https://github.com/jantimon/html-webpack-plugin/issues/1369

```
(node:11842) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tapAsync' of undefined
    at /Users/reinis/Documents/warpcloud/WARP/CODE-WEB-LIVE/valet/jcdecaux-t001-01-02-kiosk/node_modules/inline-manifest-webpack-plugin/index.js:18:18
    at SyncHook.eval [as call] (eval at create (/Users/reinis/Documents/warpcloud/WARP/CODE-WEB-LIVE/valet/jcdecaux-t001-01-02-kiosk/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:11:1)
    at Compiler.newCompilation (/Users/reinis/Documents/warpcloud/WARP/CODE-WEB-LIVE/valet/jcdecaux-t001-01-02-kiosk/node_modules/webpack/lib/Compiler.js:631:26)
    at /Users/reinis/Documents/warpcloud/WARP/CODE-WEB-LIVE/valet/jcdecaux-t001-01-02-kiosk/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/reinis/Documents/warpcloud/WARP/CODE-WEB-LIVE/valet/jcdecaux-t001-01-02-kiosk/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Compiler.compile (/Users/reinis/Documents/warpcloud/WARP/CODE-WEB-LIVE/valet/jcdecaux-t001-01-02-kiosk/node_modules/webpack/lib/Compiler.js:662:28)
    at /Users/reinis/Documents/warpcloud/WARP/CODE-WEB-LIVE/valet/jcdecaux-t001-01-02-kiosk/node_modules/webpack/lib/Compiler.js:321:11
    at Compiler.readRecords (/Users/reinis/Documents/warpcloud/WARP/CODE-WEB-LIVE/valet/jcdecaux-t001-01-02-kiosk/node_modules/webpack/lib/Compiler.js:529:11)
    at /Users/reinis/Documents/warpcloud/WARP/CODE-WEB-LIVE/valet/jcdecaux-t001-01-02-kiosk/node_modules/webpack/lib/Compiler.js:318:10
    at eval (eval at create (/Users/reinis/Documents/warpcloud/WARP/CODE-WEB-LIVE/valet/jcdecaux-t001-01-02-kiosk/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /Users/reinis/Documents/warpcloud/WARP/CODE-WEB-LIVE/valet/jcdecaux-t001-01-02-kiosk/node_modules/stylelint-webpack-plugin/dist/linter.js:48:5
(node:11842) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11842) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jantimon** [comment]
The reason here is a different one - `tapAsync` is no longer the recommended plugin interface by the webpack core team. Therefore the html-webpack-plugin changed to the new format: 

https://github.com/jantimon/html-webpack-plugin#events

**Comment by szrenwei** [comment]
Please use `react-dev-utils` instead ( https://github.com/facebook/create-react-app/tree/master/packages/react-dev-utils#new-inlinechunkhtmlpluginhtmlwebpackplugin-htmlwebpackplugin-tests-regex ), it does the same thing.

**Comment by shridevishetty18** [comment]
> Please use `react-dev-utils` instead ( https://github.com/facebook/create-react-app/tree/master/packages/react-dev-utils#new-inlinechunkhtmlpluginhtmlwebpackplugin-htmlwebpackplugin-tests-regex ), it does the same thing.

inline-manifest-webpack-plugin is not supported with webpack5. Are there any alternatives for this?
